primer_sumando = input("Pon el primer sumando:   ")
segundo_sumando = input("Pon el segundo sumando:   ")
resultado = str(int(primer_sumando) + int(segundo_sumando))
print("El resultado de la suma es: " + resultado)
input("introduce exit para salir:   ")